# Generated by Django 3.2.16 on 2022-10-17 20:48

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_full_name', models.CharField(max_length=200)),
                ('passport_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('my_emergency_contact_one_name', models.CharField(default='', max_length=200)),
                ('my_emergency_contact_one_number', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(default='', max_length=200, unique=True)),
                ('my_emergency_contact_two_name', models.CharField(default='', max_length=200)),
                ('my_emergency_contact_two_number', models.PositiveIntegerField(default=0)),
                ('my_date_of_birth', models.DateField(default='DD/MM/YY')),
                ('my_biography', models.TextField(max_length=600)),
                ('my_family', models.TextField(max_length=600)),
                ('my_likes', models.TextField(max_length=600)),
                ('my_dislikes', models.TextField(max_length=600)),
                ('my_strengths', models.TextField(max_length=600)),
                ('my_difficulties', models.TextField(max_length=600)),
                ('my_supports', models.TextField(max_length=600)),
                ('my_calming_measures', models.TextField(max_length=600)),
                ('my_communication_skills', models.TextField(max_length=600)),
                ('my_other_info', models.TextField(max_length=600)),
                ('teacher_id', models.CharField(default='', max_length=50)),
                ('pupil_id', models.PositiveIntegerField(default=0, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('my_family_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('my_favorite_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('my_hobby_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
