# Generated by Django 3.2.16 on 2022-10-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_passport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passport',
            old_name='passport_image',
            new_name='my_passport_image',
        ),
    ]
