# Generated by Django 3.2.16 on 2022-10-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_rename_passport_image_passport_my_passport_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledpupil',
            old_name='pupil_first_name',
            new_name='pupil_full_name',
        ),
        migrations.RenameField(
            model_name='passport',
            old_name='my_emergency_contact_one_name',
            new_name='my_emergency_contact_name',
        ),
        migrations.RenameField(
            model_name='passport',
            old_name='my_emergency_contact_one_number',
            new_name='my_emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='enrolledpupil',
            name='pupil_last_name',
        ),
        migrations.RemoveField(
            model_name='enrolledpupil',
            name='school_roll_no',
        ),
        migrations.RemoveField(
            model_name='enrolledpupil',
            name='teacher_name',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='my_emergency_contact_two_name',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='my_emergency_contact_two_number',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='my_family_image',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='my_favorite_image',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='my_hobby_image',
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_date_of_birth',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='pupil_id',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='passport',
            name='teacher_id',
            field=models.CharField(default='', max_length=6),
        ),
    ]
