# Generated by Django 3.2.16 on 2022-10-31 20:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0005_auto_20221026_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledpupil',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='enrolledpupil',
            name='school_roll_number',
            field=models.CharField(default='', max_length=200, verbose_name='School Roll No'),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='pupil_full_name',
            field=models.CharField(default='', max_length=200, verbose_name="Pupil's Full Name"),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='pupil_id',
            field=models.CharField(default='', max_length=8, verbose_name='Pupil ID Number'),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='school_email',
            field=models.EmailField(max_length=300, verbose_name='School Email Address'),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='school_name',
            field=models.CharField(default='', max_length=200, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_biography',
            field=models.TextField(max_length=600, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_calming_measures',
            field=models.TextField(max_length=600, verbose_name='Calming Measures'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_communication_skills_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Communication Skills Photo'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_date_of_birth',
            field=models.DateField(default='YYYY-MM-DD', verbose_name="Pupil's Date Of Birth"),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_difficulties',
            field=models.TextField(max_length=600, verbose_name='Difficulties'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_dislikes',
            field=models.TextField(max_length=600, verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_emergency_contact_name',
            field=models.CharField(default='', max_length=200, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_emergency_contact_number',
            field=models.CharField(default='', max_length=100, verbose_name='Emergency Contact Number'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_family',
            field=models.TextField(max_length=600, verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_family_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Family Photo'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_full_name',
            field=models.CharField(max_length=200, verbose_name="Pupil's Full Name"),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_likes',
            field=models.TextField(max_length=600, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_likes_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Likes Photo'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_other_info',
            field=models.TextField(max_length=600, verbose_name='Other Info'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_passport_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Passport Photo'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_strengths',
            field=models.TextField(max_length=600, verbose_name='Strengths'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_supports',
            field=models.TextField(max_length=600, verbose_name='Supports'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_supports_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Supports Photo'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='pupil_id',
            field=models.CharField(max_length=8, unique=True, verbose_name='Pupil ID Number'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='teacher_id',
            field=models.CharField(default='', max_length=6, verbose_name='Teacher ID Number'),
        ),
    ]
