# Generated by Django 3.2.16 on 2022-11-11 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0006_auto_20221031_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledpupil',
            name='pupil_id',
            field=models.CharField(default='', max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[1-9]{1}[0-9]{7}$', message='Not a valid pupil id number')], verbose_name='Pupil ID Number'),
        ),
        migrations.AlterField(
            model_name='enrolledpupil',
            name='school_roll_number',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{5}[A-Z]{1}$', message='Not a valid School Roll Number')], verbose_name='School Roll No'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_biography',
            field=models.TextField(max_length=1000, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_calming_measures',
            field=models.TextField(max_length=1000, verbose_name='Calming Measures'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_communication_skills',
            field=models.TextField(max_length=1000, verbose_name='Communication Skills'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_difficulties',
            field=models.TextField(max_length=1000, verbose_name='Difficulties'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_dislikes',
            field=models.TextField(max_length=1000, verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_family',
            field=models.TextField(max_length=1000, verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_likes',
            field=models.TextField(max_length=1000, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_other_info',
            field=models.TextField(max_length=1000, verbose_name='Other Info'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_strengths',
            field=models.TextField(max_length=1000, verbose_name='Strengths'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_supports',
            field=models.TextField(max_length=1000, verbose_name='Supports'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='pupil_id',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{8}$', message='Not a valid pupil id number')], verbose_name='Pupil ID Number'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='teacher_id',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^[0-7]{6}$', message='Not a valid Teacher ID')], verbose_name='Teacher ID Number'),
        ),
    ]
