# Generated by Django 3.2.16 on 2022-11-16 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0007_auto_20221111_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledpupil',
            name='school_roll_number',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{5}[A-Za-z]{1}$', message='Not a valid School Roll Number')], verbose_name='School Roll No'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_biography',
            field=models.TextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_calming_measures',
            field=models.TextField(verbose_name='Calming Measures'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_communication_skills',
            field=models.TextField(verbose_name='Communication Skills'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_difficulties',
            field=models.TextField(verbose_name='Difficulties'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_dislikes',
            field=models.TextField(verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_family',
            field=models.TextField(verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_likes',
            field=models.TextField(verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_other_info',
            field=models.TextField(verbose_name='Other Info'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_strengths',
            field=models.TextField(verbose_name='Strengths'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='my_supports',
            field=models.TextField(verbose_name='Supports'),
        ),
    ]
